### ISSUE TITLE
Update HASPA HBCI URL

### ISSUE THREAD

**Issue by svenstaro** [jhermsmeier/fints-institute-db#1]
Haspa is changing their HBCI URL to banking-hh7.s-fints-pt-hh.de/fints30 on 2019-04-20.

Source: https://www.willuhn.de/wiki/doku.php?id=haspa-migration

**Comment by jhermsmeier** [comment]
Hey, thanks for bringing it up – I won't change it manually though, because this has been a semi-automatic dump of data from the HBCI-ZKA. They keep making the process of getting the data more bureaucratic by the years, and I've lost access in mid 2018.
I'll see to regaining access, if time permits.

**Comment by svenstaro** [comment]
I assumed so and see what you mean. That really is too bad. Hopefully you can regain access. If you can't regain it, would you consider changing that little thing manually or would this repo be effectively frozen then?

**Comment by jhermsmeier** [comment]
Yeah, they're being really apprehensive about their data (which is / should be public anyway), and now require you to register your "product" in order to get it:

> Zur Erfüllung der Vorgaben aus MaSI und PSD2 bzgl. der Transparenz über die auf Kundenseite eingesetzte Software wird die Deutsche Kreditwirtschaft einen Prozess zur Registrierung von FinTS-Produkten etablieren, um gegenüber den Kunden Informationen bzgl. der FinTS-Nutzung nachweisen zu können.

I'll give it a try, but suspect they'll be denying access, as this isn't a commercial product (which is yet another one of their requirements). Should it fail, I'll switch this repository over to manual, and look for alternative data sources.

**Comment by svenstaro** [comment]
Thanks for not dropping the ball. I'm also somewhat immersed in this German
banking thing and know just how incredibly tedious it is.

**Comment by jhermsmeier** [comment]
I've sent them the registration form more than a week ago, and haven't heard back from them yet. It's supposed to yield a response within 5 days, but it's been easter... not quite sure when to call it. I guess if they haven't answered within another week, I'll start looking for an alternate source.

**Comment by svenstaro** [comment]
Sounds reasonable.

**Comment by svenstaro** [comment]
Just to note, I'm now using this source: https://raw.githubusercontent.com/hbci4j/hbci4java/0072d401187a69a451eae1cbe928da3e2be6109f/src/main/resources/blz.properties

**Comment by jhermsmeier** [comment]
Partial success! I did get a response with a registration number from them, but it's addressed to someone else :D I apparently still got signed up for the data, as I got that too, so here's me hoping it'll stay that way, and that the registration will be corrected.

**Comment by jhermsmeier** [comment]
Closing this for now, as I've updated the data now. I'll let you know if anything else happens regarding the registration, etc.

**Comment by svenstaro** [comment]
Ok cool. Nice. ;)
